[package]
name = "yahaha"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.6.2"
thrussh = "0.35.1"
tokio = { version = "1.35.1", features = ["full"] }
anyhow = "1.0"
futures = "0.3.17"